CREATE DATABASE IF NOT EXISTS municipio_indicencias_db;
USE municipio_indicencias_db;

CREATE TABLE Ciudadanos (
    ID_CIUDADANO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    DNI INT(8) NOT NULL UNIQUE,
    TELEFONO VARCHAR(255) NOT NULL,
    LOCALIDAD VARCHAR(255) NOT NULL
);

CREATE TABLE Usuarios (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    GMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL DEFAULT 'usuario',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_CIUDADANO INT NOT NULL,
    CONSTRAINT FK_ID_CIUDADANO FOREIGN KEY (ID_CIUDADANO)
        REFERENCES Ciudadanos(ID_CIUDADANO)
);

CREATE TABLE Incidentes (
    ID_INCIDENTE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_INCIDENTE VARCHAR(255) NOT NULL,
    DETALLES VARCHAR(500) NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_ID_USUARIO_INCIDENTE FOREIGN KEY (ID_USUARIO)
        REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Alerta (
    ID_ALERTA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_ALERTA VARCHAR(255) NOT NULL,
    MENSAJE VARCHAR(500) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR(255),
    ID_INCIDENTE_ALERTA INT NOT NULL,
    CONSTRAINT FK_ID_INCIDENTE_ALERTA FOREIGN KEY (ID_INCIDENTE_ALERTA)
        REFERENCES Incidentes(ID_INCIDENTE)
);

CREATE TABLE Reportes (
    ID_REPORTE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_INICIO DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL DEFAULT 'pendiente',
    ID_INCIDENTE_REPORTES INT NOT NULL,
    CONSTRAINT FK_ID_INCIDENTE_REPORTES FOREIGN KEY (ID_INCIDENTE_REPORTES)
        REFERENCES Incidentes(ID_INCIDENTE)
);

CREATE TABLE Usuario_Reporte (
    ID_USUARIO INT NOT NULL,
    ID_REPORTE INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_REPORTE),
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO),
    CONSTRAINT FK_ID_REPORTE FOREIGN KEY (ID_REPORTE) REFERENCES Reportes(ID_REPORTE)
);