use municipio_indicencias_db;

CREATE TABLE Cuidadanos (
    ID_CUIDADANO int PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    DNI VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    LOCALIDAD VARCHAR(255) NOT NULL
);

CREATE TABLE Usuarios (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    GMAIL VARCHAR(255) NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL,
    ID_CUIDADANO INT NOT NULL,
    CONSTRAINT FK_ID_CUIDADANO FOREIGN KEY (ID_CUIDADANO) 
    REFERENCES Cuidadanos(ID_CUIDADANO)
);

CREATE TABLE Incidentes(
    ID_INCIDENTE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_INCIDENTE VARCHAR(255) NOT NULL,
    DETALLES VARCHAR(500) NOT NULL,
    UBICACION VARCHAR(255) NOT NULL
);

CREATE TABLE Alerta(
    ID_ALERTA int PRIMARY KEY AUTO_INCREMENT,
    TIPO_ALERTA VARCHAR(255) NOT NULL,
    MENSAJE VARCHAR(500) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR(255),
    ID_INCIDENTE_ALERTA INT NOT NULL,
    CONSTRAINT FK_ID_INCIDENTE_ALERTA FOREIGN KEY (ID_INCIDENTE_ALERTA) 
    REFERENCES Incidentes(ID_INCIDENTE)
);

CREATE TABLE Reportes(
    ID_REPORTE int PRIMARY KEY AUTO_INCREMENT,
    FECHA_INICIO DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    ID_INCIDENTE_REPORTES INT NOT NULL,
    CONSTRAINT FK_ID_INCIDENTE_REPORTES FOREIGN KEY (ID_INCIDENTE_REPORTES) 
    REFERENCES Incidentes(ID_INCIDENTE)
);

CREATE TABLE Usuario_Reporte(
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO),
    ID_REPORTE INT NOT NULL,
    CONSTRAINT FK_ID_REPORTE FOREIGN KEY (ID_REPORTE) REFERENCES Reportes(ID_REPORTE)
);