CREATE DATABASE IF NOT EXISTS municipio_indicencias_db;
USE municipio_indicencias_db;

CREATE TABLE Ciudadanos (
    ID_CIUDADANO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    DNI INT(8) NOT NULL UNIQUE,
    TELEFONO VARCHAR(255) NOT NULL,
    LOCALIDAD VARCHAR(255) NOT NULL,
    CODIGO_POSTAL INT NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    FOTO_PERFIL VARCHAR(255) NOT NULL DEFAULT 'img/default-profile.png'
);

CREATE TABLE Usuarios (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    GMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL DEFAULT 'usuario',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_CIUDADANO INT NOT NULL,
    CONSTRAINT FK_ID_CIUDADANO FOREIGN KEY (ID_CIUDADANO)
        REFERENCES Ciudadanos(ID_CIUDADANO)
);

CREATE TABLE Incidentes (
    ID_INCIDENTE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_INCIDENTE VARCHAR(255) NOT NULL,
    DETALLES VARCHAR(500) NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IMAGEN VARCHAR(255),
    ID_USUARIO INT NOT NULL,
    ESTADO VARCHAR(255) NOT NULL DEFAULT 'PENDIENTE',
    FECHA_MODIFICACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ID_USUARIO_INCIDENTE FOREIGN KEY (ID_USUARIO)
        REFERENCES Usuarios(ID_USUARIO)
);